# Generated by Django 5.2.4 on 2025-07-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade_level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('badge_name', models.CharField(default='Knowledge Seeker', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('choices', models.CharField(max_length=255)),
                ('correct_choice', models.PositiveSmallIntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('sandbox_greenhouse', 'Sandbox: Virtual Greenhouse'), ('quiz', 'Quiz'), ('challenge', 'Reverse-Engineer Challenge')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topic_images/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='topics.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
