# Generated by Django 5.2.4 on 2025-07-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade_level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('badge_name', models.CharField(default='Knowledge Seeker', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('content_html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('choices', models.CharField(max_length=255)),
                ('correct_choice', models.PositiveSmallIntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.topic')),
            ],
        ),
    ]
